language: elixir
cache:
  directories:
    - _build
    - deps
services:
  - docker
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker credentials
    - secure: "C6haKHmvzJXMRRvPSuH4w5hOVuNb7MHfGhWjr2vVJu9Ms8cnBAbSos6lNLCrnC6suWqZab5De7ETatJf87qI4SREA2dcdzGfEprUhhxxx5nlDzGoG67DbeWR5uBMXD1AUv3kXr+K0iDpz2gYM9TVupISI2l4gHDH9k2hoznIOoj3ttip/h/G9ofjR4uGlkPJx0SOXn10frj4OJL0LaRbmLVavL5KHoU3O3rIC0bYTqFxNamp8nw6aJqlVrnG2ByfHN9DqQuDID+1BH0q/e1TXVzR7kumpXaLKxAbfOuR42Ew7G6qDFNnPswWu9wdIL7zVydvVBZBhftSB4R1qu8ApZi8QSPsH9+6RHz3aEswmBf7flryDVVjbAiMthcT8uPoUiBBNZU1TJYYCtTqHoZoxyd5lIr8MIQ33Xf65FdYWOT9M0zoCIUYMJSJ0ks+98Xmo+JqZ9RmB4xgMQNeKChnX6MxHH3yrp4ZfNO18gLVA2wHlRcnFaAdUaDHYtTrpWjE5oMY6yEqa4je6QFC5frPqDN7qpoI7SDFVExp2rq9YyvpTR/BZ9Ve36YIwBM9l4yUR69R0+NlDEHwkX9CWEoDZa5cg98qAWWuf5j6CXbxpLI0yRdQup2IYtoU/jG/zSzhqkkSZH9ZzTxWjwlQXkFGkHD4GH1Xpt6slX2T9lcNdMU="
    - secure: "UgV7uA0/dQlYmoONdpMjGrPEfZfPkFeB5tPjfcasgGgwh3EwCCjNkWntx9tbTDHl1RNErfXuHuykkV7WKEd3RXsrMYkWFR+Swqfq9d0yQ56oB6EjYLMEmWwJ1nTHdUDghvQiG+2mJjduGHOiNGWQnSAnLUknXZO4Cgry8djVlyGm+jP+O8j/3B6OrpLXjmoVnn236dL4r1TK3zLousnWkh24MQKTN65qZ0dVms980SPoVrNZ4Yyc4hi2+Xr9FNt9b2EA2NrclS6E+EWWYRfJ9NV/xGRlfq/gk14FUvLZye7DXPdoipXHqMphLagmHB0EMruUoJDMAMXOOfOLANVMPZw492+GaCdes3abhu/U0ooJuBgeXGTi7BLNu7xPsE+WKaqOG07yg+3E/vnItAZ9Ym7ONBvvWLSkkhMqCvA6n4QBPpfb4Ja2D1+HysmZztVqsj2FPYJEEJoRC1akxkjlL1S+r5o5WdStQBHH54mFGyzqKd+PHmhnGckf5Eryq8sOUxI+afEamH1ioyfMDOZM7V5mhP8SlVHkbLG1OvyuKl7h3BEPnwAk7zvFoK87o2mb4Zp/APuPYvctnC1H4sxD7OJrrt5ANLfhP7cGqZi6y79Kh2O58rvvis4Hi8FdkYPk+eRIRZ+cexftJT2SovSRjGC/08CzD3C4BycONj2gdtw="

before_install:
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Run Docker container
  - ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs ehealth --details --since 5h; exit 1; fi;
after_failure:
  - docker logs ehealth --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh